### ISSUE TITLE
存在偶现 crash 

### ISSUE THREAD

**Issue by chenhengjie123** [testerhome/A-Native-TesterHome#6]
原帖位置：https://testerhome.com/topics/3772#reply2

环境：
testerhome版本：v1.0.1 build 10119
android:4.4.2
终端：荣耀6 EMUI3.0

描述：首页进入帖子返回列表时偶现的Crash,没能复现

Log：

```
E/AndroidRuntime( 5302): FATAL EXCEPTION: main

E/AndroidRuntime( 5302): Process: com.testerhome.nativeandroid, PID: 5302

E/AndroidRuntime( 5302): java.lang.NullPointerException

E/AndroidRuntime( 5302):    at com.testerhome.nativeandroid.views.f.onResponse(Unknown Source)

E/AndroidRuntime( 5302):    at retrofit.ExecutorCallAdapterFactory$ExecutorCallback$1.run(Unknown Source)

E/AndroidRuntime( 5302):    at android.os.Handler.handleCallback(Handler.java:733)

E/AndroidRuntime( 5302):    at android.os.Handler.dispatchMessage(Handler.java:95)

E/AndroidRuntime( 5302):    at android.os.Looper.loop(Looper.java:136)

E/AndroidRuntime( 5302):    at android.app.ActivityThread.main(ActivityThread.java:5314)

E/AndroidRuntime( 5302):    at java.lang.reflect.Method.invokeNative(Native Method)

E/AndroidRuntime( 5302):    at java.lang.reflect.Method.invoke(Method.java:515)

E/AndroidRuntime( 5302):    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:864)

E/AndroidRuntime( 5302):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:680)

E/AndroidRuntime( 5302):    at dalvik.system.NativeStart.main(Native Method)

W/DropBoxManagerService( 2938): Dropping: data_app_crash (899 > 0 bytes)

W/ActivityManager( 2938):   Force finishing activity com.testerhome.nativeandroid/.views.MainActivity
```

**Comment by sxyy** [comment]
这bug应该都是弱网情况下导致的问题。1.0.3版本应该是解决这个问题了。
