### ISSUE TITLE
testerhome 移动版 crash

### ISSUE THREAD

**Issue by chenhengjie123** [testerhome/A-Native-TesterHome#7]
源地址：https://testerhome.com/topics/3836

在1台手机上和模拟器上 运行com.testerhome.nativeandroid后，进入任意主题，对回复控件输入任何文字，点击发送。导致testerhome 移动版 crash
出现概率100%
手机环境：mi4w os 4.4.4
模拟器： os:6.0 、5.0.2 

捉取"debug"日志内容如下（省略了AndroidRuntime）

``` java
tag:AndroidRuntime 
FATAL EXCEPTION: main       
Process: com.testerhome.nativeandroid, PID: 8813        
java.lang.NullPointerException: Attempt to invoke virtual method 'java.util.List com.testerhome.nativeandroid.models.CreateReplyResponse.getError()' on a null object reference     
    at com.testerhome.nativeandroid.views.i.onResponse(Unknown Source)      
    at retrofit.ExecutorCallAdapterFactory$ExecutorCallback$1.run(Unknown Source)       
    at android.os.Handler.handleCallback(Handler.java:739)      
    at android.os.Handler.dispatchMessage(Handler.java:95)      
    at android.os.Looper.loop(Looper.java:145)      
    at android.app.ActivityThread.main(ActivityThread.java:6136)        
    at java.lang.reflect.Method.invoke(Native Method)       
    at java.lang.reflect.Method.invoke(Method.java:372)     
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1399)     
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1194)
```

**Comment by sxyy** [comment]
@chenhengjie123  新版本上试试看有没有这个问题？我在新版本已经把这个代码去掉了。
